/*
 * ConverLattice.cpp
 *
 *  Created on: Jul 8, 2012
 *      Author: spiem_01
 */

#include "ConvertLattice.h"
#include "Environment.h"
#include <iomanip>

namespace Update {

ConvertLattice::ConvertLattice() { }

ConvertLattice::~ConvertLattice() { }

template<typename To, typename From> void ConvertLattice::convert(To& adjointLattice, const From& fundamentalLattice) {
	//Calculate the conversion
#pragma omp parallel for
	for (int site = 0; site < adjointLattice.localsize; ++site) {
		for (unsigned int mu = 0; mu < 4; ++mu) {
#if NUMCOLORS == 2
			adjointLattice[site][mu].at(0, 0) = (imag(fundamentalLattice[site][mu].at(0, 1)))*(imag(fundamentalLattice[site][mu].at(1, 0)))+(imag(fundamentalLattice[site][mu].at(0, 0)))*(imag(fundamentalLattice[site][mu].at(1, 1)))+(real(fundamentalLattice[site][mu].at(0, 1)))*(real(fundamentalLattice[site][mu].at(1, 0)))+(real(fundamentalLattice[site][mu].at(0, 0)))*(real(fundamentalLattice[site][mu].at(1, 1)));
			adjointLattice[site][mu].at(0, 1) = -((imag(fundamentalLattice[site][mu].at(1, 1)))*(real(fundamentalLattice[site][mu].at(0, 0))))+(imag(fundamentalLattice[site][mu].at(1, 0)))*(real(fundamentalLattice[site][mu].at(0, 1)))-((imag(fundamentalLattice[site][mu].at(0, 1)))*(real(fundamentalLattice[site][mu].at(1, 0))))+(imag(fundamentalLattice[site][mu].at(0, 0)))*(real(fundamentalLattice[site][mu].at(1, 1)));
			adjointLattice[site][mu].at(0, 2) = (imag(fundamentalLattice[site][mu].at(0, 0)))*(imag(fundamentalLattice[site][mu].at(1, 0)))-((imag(fundamentalLattice[site][mu].at(0, 1)))*(imag(fundamentalLattice[site][mu].at(1, 1))))+(real(fundamentalLattice[site][mu].at(0, 0)))*(real(fundamentalLattice[site][mu].at(1, 0)))-((real(fundamentalLattice[site][mu].at(0, 1)))*(real(fundamentalLattice[site][mu].at(1, 1))));
			adjointLattice[site][mu].at(1, 0) = (imag(fundamentalLattice[site][mu].at(1, 1)))*(real(fundamentalLattice[site][mu].at(0, 0)))+(imag(fundamentalLattice[site][mu].at(1, 0)))*(real(fundamentalLattice[site][mu].at(0, 1)))-((imag(fundamentalLattice[site][mu].at(0, 1)))*(real(fundamentalLattice[site][mu].at(1, 0))))-((imag(fundamentalLattice[site][mu].at(0, 0)))*(real(fundamentalLattice[site][mu].at(1, 1))));
			adjointLattice[site][mu].at(1, 1) = -((imag(fundamentalLattice[site][mu].at(0, 1)))*(imag(fundamentalLattice[site][mu].at(1, 0))))+(imag(fundamentalLattice[site][mu].at(0, 0)))*(imag(fundamentalLattice[site][mu].at(1, 1)))-((real(fundamentalLattice[site][mu].at(0, 1)))*(real(fundamentalLattice[site][mu].at(1, 0))))+(real(fundamentalLattice[site][mu].at(0, 0)))*(real(fundamentalLattice[site][mu].at(1, 1)));
			adjointLattice[site][mu].at(1, 2) = (imag(fundamentalLattice[site][mu].at(1, 0)))*(real(fundamentalLattice[site][mu].at(0, 0)))-((imag(fundamentalLattice[site][mu].at(1, 1)))*(real(fundamentalLattice[site][mu].at(0, 1))))-((imag(fundamentalLattice[site][mu].at(0, 0)))*(real(fundamentalLattice[site][mu].at(1, 0))))+(imag(fundamentalLattice[site][mu].at(0, 1)))*(real(fundamentalLattice[site][mu].at(1, 1)));
			adjointLattice[site][mu].at(2, 0) = (imag(fundamentalLattice[site][mu].at(0, 0)))*(imag(fundamentalLattice[site][mu].at(0, 1)))-((imag(fundamentalLattice[site][mu].at(1, 0)))*(imag(fundamentalLattice[site][mu].at(1, 1))))+(real(fundamentalLattice[site][mu].at(0, 0)))*(real(fundamentalLattice[site][mu].at(0, 1)))-((real(fundamentalLattice[site][mu].at(1, 0)))*(real(fundamentalLattice[site][mu].at(1, 1))));
			adjointLattice[site][mu].at(2, 1) = -((imag(fundamentalLattice[site][mu].at(0, 1)))*(real(fundamentalLattice[site][mu].at(0, 0))))+(imag(fundamentalLattice[site][mu].at(0, 0)))*(real(fundamentalLattice[site][mu].at(0, 1)))+(imag(fundamentalLattice[site][mu].at(1, 1)))*(real(fundamentalLattice[site][mu].at(1, 0)))-((imag(fundamentalLattice[site][mu].at(1, 0)))*(real(fundamentalLattice[site][mu].at(1, 1))));
			adjointLattice[site][mu].at(2, 2) = 0.5*((imag(fundamentalLattice[site][mu].at(0, 0)))*(imag(fundamentalLattice[site][mu].at(0, 0)))-((imag(fundamentalLattice[site][mu].at(0, 1)))*(imag(fundamentalLattice[site][mu].at(0, 1))))-((imag(fundamentalLattice[site][mu].at(1, 0)))*(imag(fundamentalLattice[site][mu].at(1, 0))))+(imag(fundamentalLattice[site][mu].at(1, 1)))*(imag(fundamentalLattice[site][mu].at(1, 1)))+(real(fundamentalLattice[site][mu].at(0, 0)))*(real(fundamentalLattice[site][mu].at(0, 0)))-((real(fundamentalLattice[site][mu].at(0, 1)))*(real(fundamentalLattice[site][mu].at(0, 1))))-((real(fundamentalLattice[site][mu].at(1, 0)))*(real(fundamentalLattice[site][mu].at(1, 0))))+(real(fundamentalLattice[site][mu].at(1, 1)))*(real(fundamentalLattice[site][mu].at(1, 1))));
#endif
#if NUMCOLORS == 3
			adjointLattice[site][mu].at(0, 0) = (imag(fundamentalLattice[site][mu].at(0, 1)))*(imag(fundamentalLattice[site][mu].at(1, 0)))+(imag(fundamentalLattice[site][mu].at(0, 0)))*(imag(fundamentalLattice[site][mu].at(1, 1)))+(real(fundamentalLattice[site][mu].at(0, 1)))*(real(fundamentalLattice[site][mu].at(1, 0)))+(real(fundamentalLattice[site][mu].at(0, 0)))*(real(fundamentalLattice[site][mu].at(1, 1)));
			adjointLattice[site][mu].at(0, 1) = (imag(fundamentalLattice[site][mu].at(0, 2)))*(imag(fundamentalLattice[site][mu].at(1, 0)))+(imag(fundamentalLattice[site][mu].at(0, 0)))*(imag(fundamentalLattice[site][mu].at(1, 2)))+(real(fundamentalLattice[site][mu].at(0, 2)))*(real(fundamentalLattice[site][mu].at(1, 0)))+(real(fundamentalLattice[site][mu].at(0, 0)))*(real(fundamentalLattice[site][mu].at(1, 2)));
			adjointLattice[site][mu].at(0, 2) = (imag(fundamentalLattice[site][mu].at(0, 2)))*(imag(fundamentalLattice[site][mu].at(1, 1)))+(imag(fundamentalLattice[site][mu].at(0, 1)))*(imag(fundamentalLattice[site][mu].at(1, 2)))+(real(fundamentalLattice[site][mu].at(0, 2)))*(real(fundamentalLattice[site][mu].at(1, 1)))+(real(fundamentalLattice[site][mu].at(0, 1)))*(real(fundamentalLattice[site][mu].at(1, 2)));
			adjointLattice[site][mu].at(0, 3) = -((imag(fundamentalLattice[site][mu].at(1, 1)))*(real(fundamentalLattice[site][mu].at(0, 0))))+(imag(fundamentalLattice[site][mu].at(1, 0)))*(real(fundamentalLattice[site][mu].at(0, 1)))-((imag(fundamentalLattice[site][mu].at(0, 1)))*(real(fundamentalLattice[site][mu].at(1, 0))))+(imag(fundamentalLattice[site][mu].at(0, 0)))*(real(fundamentalLattice[site][mu].at(1, 1)));
			adjointLattice[site][mu].at(0, 4) = -((imag(fundamentalLattice[site][mu].at(1, 2)))*(real(fundamentalLattice[site][mu].at(0, 0))))+(imag(fundamentalLattice[site][mu].at(1, 0)))*(real(fundamentalLattice[site][mu].at(0, 2)))-((imag(fundamentalLattice[site][mu].at(0, 2)))*(real(fundamentalLattice[site][mu].at(1, 0))))+(imag(fundamentalLattice[site][mu].at(0, 0)))*(real(fundamentalLattice[site][mu].at(1, 2)));
			adjointLattice[site][mu].at(0, 5) = -((imag(fundamentalLattice[site][mu].at(1, 2)))*(real(fundamentalLattice[site][mu].at(0, 1))))+(imag(fundamentalLattice[site][mu].at(1, 1)))*(real(fundamentalLattice[site][mu].at(0, 2)))-((imag(fundamentalLattice[site][mu].at(0, 2)))*(real(fundamentalLattice[site][mu].at(1, 1))))+(imag(fundamentalLattice[site][mu].at(0, 1)))*(real(fundamentalLattice[site][mu].at(1, 2)));
			adjointLattice[site][mu].at(0, 6) = (imag(fundamentalLattice[site][mu].at(0, 0)))*(imag(fundamentalLattice[site][mu].at(1, 0)))-((imag(fundamentalLattice[site][mu].at(0, 1)))*(imag(fundamentalLattice[site][mu].at(1, 1))))+(real(fundamentalLattice[site][mu].at(0, 0)))*(real(fundamentalLattice[site][mu].at(1, 0)))-((real(fundamentalLattice[site][mu].at(0, 1)))*(real(fundamentalLattice[site][mu].at(1, 1))));
			adjointLattice[site][mu].at(0, 7) = (imag(fundamentalLattice[site][mu].at(0, 0)))*(imag(fundamentalLattice[site][mu].at(1, 0)))/sqrt(3)+(imag(fundamentalLattice[site][mu].at(0, 1)))*(imag(fundamentalLattice[site][mu].at(1, 1)))/sqrt(3)+(-2)*((imag(fundamentalLattice[site][mu].at(0, 2)))*(imag(fundamentalLattice[site][mu].at(1, 2))))/sqrt(3)+(real(fundamentalLattice[site][mu].at(0, 0)))*(real(fundamentalLattice[site][mu].at(1, 0)))/sqrt(3)+(real(fundamentalLattice[site][mu].at(0, 1)))*(real(fundamentalLattice[site][mu].at(1, 1)))/sqrt(3)+(-2)*((real(fundamentalLattice[site][mu].at(0, 2)))*(real(fundamentalLattice[site][mu].at(1, 2))))/sqrt(3);
			adjointLattice[site][mu].at(1, 0) = (imag(fundamentalLattice[site][mu].at(0, 1)))*(imag(fundamentalLattice[site][mu].at(2, 0)))+(imag(fundamentalLattice[site][mu].at(0, 0)))*(imag(fundamentalLattice[site][mu].at(2, 1)))+(real(fundamentalLattice[site][mu].at(0, 1)))*(real(fundamentalLattice[site][mu].at(2, 0)))+(real(fundamentalLattice[site][mu].at(0, 0)))*(real(fundamentalLattice[site][mu].at(2, 1)));
			adjointLattice[site][mu].at(1, 1) = (imag(fundamentalLattice[site][mu].at(0, 2)))*(imag(fundamentalLattice[site][mu].at(2, 0)))+(imag(fundamentalLattice[site][mu].at(0, 0)))*(imag(fundamentalLattice[site][mu].at(2, 2)))+(real(fundamentalLattice[site][mu].at(0, 2)))*(real(fundamentalLattice[site][mu].at(2, 0)))+(real(fundamentalLattice[site][mu].at(0, 0)))*(real(fundamentalLattice[site][mu].at(2, 2)));
			adjointLattice[site][mu].at(1, 2) = (imag(fundamentalLattice[site][mu].at(0, 2)))*(imag(fundamentalLattice[site][mu].at(2, 1)))+(imag(fundamentalLattice[site][mu].at(0, 1)))*(imag(fundamentalLattice[site][mu].at(2, 2)))+(real(fundamentalLattice[site][mu].at(0, 2)))*(real(fundamentalLattice[site][mu].at(2, 1)))+(real(fundamentalLattice[site][mu].at(0, 1)))*(real(fundamentalLattice[site][mu].at(2, 2)));
			adjointLattice[site][mu].at(1, 3) = -((imag(fundamentalLattice[site][mu].at(2, 1)))*(real(fundamentalLattice[site][mu].at(0, 0))))+(imag(fundamentalLattice[site][mu].at(2, 0)))*(real(fundamentalLattice[site][mu].at(0, 1)))-((imag(fundamentalLattice[site][mu].at(0, 1)))*(real(fundamentalLattice[site][mu].at(2, 0))))+(imag(fundamentalLattice[site][mu].at(0, 0)))*(real(fundamentalLattice[site][mu].at(2, 1)));
			adjointLattice[site][mu].at(1, 4) = -((imag(fundamentalLattice[site][mu].at(2, 2)))*(real(fundamentalLattice[site][mu].at(0, 0))))+(imag(fundamentalLattice[site][mu].at(2, 0)))*(real(fundamentalLattice[site][mu].at(0, 2)))-((imag(fundamentalLattice[site][mu].at(0, 2)))*(real(fundamentalLattice[site][mu].at(2, 0))))+(imag(fundamentalLattice[site][mu].at(0, 0)))*(real(fundamentalLattice[site][mu].at(2, 2)));
			adjointLattice[site][mu].at(1, 5) = -((imag(fundamentalLattice[site][mu].at(2, 2)))*(real(fundamentalLattice[site][mu].at(0, 1))))+(imag(fundamentalLattice[site][mu].at(2, 1)))*(real(fundamentalLattice[site][mu].at(0, 2)))-((imag(fundamentalLattice[site][mu].at(0, 2)))*(real(fundamentalLattice[site][mu].at(2, 1))))+(imag(fundamentalLattice[site][mu].at(0, 1)))*(real(fundamentalLattice[site][mu].at(2, 2)));
			adjointLattice[site][mu].at(1, 6) = (imag(fundamentalLattice[site][mu].at(0, 0)))*(imag(fundamentalLattice[site][mu].at(2, 0)))-((imag(fundamentalLattice[site][mu].at(0, 1)))*(imag(fundamentalLattice[site][mu].at(2, 1))))+(real(fundamentalLattice[site][mu].at(0, 0)))*(real(fundamentalLattice[site][mu].at(2, 0)))-((real(fundamentalLattice[site][mu].at(0, 1)))*(real(fundamentalLattice[site][mu].at(2, 1))));
			adjointLattice[site][mu].at(1, 7) = (imag(fundamentalLattice[site][mu].at(0, 0)))*(imag(fundamentalLattice[site][mu].at(2, 0)))/sqrt(3)+(imag(fundamentalLattice[site][mu].at(0, 1)))*(imag(fundamentalLattice[site][mu].at(2, 1)))/sqrt(3)+(-2)*((imag(fundamentalLattice[site][mu].at(0, 2)))*(imag(fundamentalLattice[site][mu].at(2, 2))))/sqrt(3)+(real(fundamentalLattice[site][mu].at(0, 0)))*(real(fundamentalLattice[site][mu].at(2, 0)))/sqrt(3)+(real(fundamentalLattice[site][mu].at(0, 1)))*(real(fundamentalLattice[site][mu].at(2, 1)))/sqrt(3)+(-2)*((real(fundamentalLattice[site][mu].at(0, 2)))*(real(fundamentalLattice[site][mu].at(2, 2))))/sqrt(3);
			adjointLattice[site][mu].at(2, 0) = (imag(fundamentalLattice[site][mu].at(1, 1)))*(imag(fundamentalLattice[site][mu].at(2, 0)))+(imag(fundamentalLattice[site][mu].at(1, 0)))*(imag(fundamentalLattice[site][mu].at(2, 1)))+(real(fundamentalLattice[site][mu].at(1, 1)))*(real(fundamentalLattice[site][mu].at(2, 0)))+(real(fundamentalLattice[site][mu].at(1, 0)))*(real(fundamentalLattice[site][mu].at(2, 1)));
			adjointLattice[site][mu].at(2, 1) = (imag(fundamentalLattice[site][mu].at(1, 2)))*(imag(fundamentalLattice[site][mu].at(2, 0)))+(imag(fundamentalLattice[site][mu].at(1, 0)))*(imag(fundamentalLattice[site][mu].at(2, 2)))+(real(fundamentalLattice[site][mu].at(1, 2)))*(real(fundamentalLattice[site][mu].at(2, 0)))+(real(fundamentalLattice[site][mu].at(1, 0)))*(real(fundamentalLattice[site][mu].at(2, 2)));
			adjointLattice[site][mu].at(2, 2) = (imag(fundamentalLattice[site][mu].at(1, 2)))*(imag(fundamentalLattice[site][mu].at(2, 1)))+(imag(fundamentalLattice[site][mu].at(1, 1)))*(imag(fundamentalLattice[site][mu].at(2, 2)))+(real(fundamentalLattice[site][mu].at(1, 2)))*(real(fundamentalLattice[site][mu].at(2, 1)))+(real(fundamentalLattice[site][mu].at(1, 1)))*(real(fundamentalLattice[site][mu].at(2, 2)));
			adjointLattice[site][mu].at(2, 3) = -((imag(fundamentalLattice[site][mu].at(2, 1)))*(real(fundamentalLattice[site][mu].at(1, 0))))+(imag(fundamentalLattice[site][mu].at(2, 0)))*(real(fundamentalLattice[site][mu].at(1, 1)))-((imag(fundamentalLattice[site][mu].at(1, 1)))*(real(fundamentalLattice[site][mu].at(2, 0))))+(imag(fundamentalLattice[site][mu].at(1, 0)))*(real(fundamentalLattice[site][mu].at(2, 1)));
			adjointLattice[site][mu].at(2, 4) = -((imag(fundamentalLattice[site][mu].at(2, 2)))*(real(fundamentalLattice[site][mu].at(1, 0))))+(imag(fundamentalLattice[site][mu].at(2, 0)))*(real(fundamentalLattice[site][mu].at(1, 2)))-((imag(fundamentalLattice[site][mu].at(1, 2)))*(real(fundamentalLattice[site][mu].at(2, 0))))+(imag(fundamentalLattice[site][mu].at(1, 0)))*(real(fundamentalLattice[site][mu].at(2, 2)));
			adjointLattice[site][mu].at(2, 5) = -((imag(fundamentalLattice[site][mu].at(2, 2)))*(real(fundamentalLattice[site][mu].at(1, 1))))+(imag(fundamentalLattice[site][mu].at(2, 1)))*(real(fundamentalLattice[site][mu].at(1, 2)))-((imag(fundamentalLattice[site][mu].at(1, 2)))*(real(fundamentalLattice[site][mu].at(2, 1))))+(imag(fundamentalLattice[site][mu].at(1, 1)))*(real(fundamentalLattice[site][mu].at(2, 2)));
			adjointLattice[site][mu].at(2, 6) = (imag(fundamentalLattice[site][mu].at(1, 0)))*(imag(fundamentalLattice[site][mu].at(2, 0)))-((imag(fundamentalLattice[site][mu].at(1, 1)))*(imag(fundamentalLattice[site][mu].at(2, 1))))+(real(fundamentalLattice[site][mu].at(1, 0)))*(real(fundamentalLattice[site][mu].at(2, 0)))-((real(fundamentalLattice[site][mu].at(1, 1)))*(real(fundamentalLattice[site][mu].at(2, 1))));
			adjointLattice[site][mu].at(2, 7) = (imag(fundamentalLattice[site][mu].at(1, 0)))*(imag(fundamentalLattice[site][mu].at(2, 0)))/sqrt(3)+(imag(fundamentalLattice[site][mu].at(1, 1)))*(imag(fundamentalLattice[site][mu].at(2, 1)))/sqrt(3)+(-2)*((imag(fundamentalLattice[site][mu].at(1, 2)))*(imag(fundamentalLattice[site][mu].at(2, 2))))/sqrt(3)+(real(fundamentalLattice[site][mu].at(1, 0)))*(real(fundamentalLattice[site][mu].at(2, 0)))/sqrt(3)+(real(fundamentalLattice[site][mu].at(1, 1)))*(real(fundamentalLattice[site][mu].at(2, 1)))/sqrt(3)+(-2)*((real(fundamentalLattice[site][mu].at(1, 2)))*(real(fundamentalLattice[site][mu].at(2, 2))))/sqrt(3);
			adjointLattice[site][mu].at(3, 0) = (imag(fundamentalLattice[site][mu].at(1, 1)))*(real(fundamentalLattice[site][mu].at(0, 0)))+(imag(fundamentalLattice[site][mu].at(1, 0)))*(real(fundamentalLattice[site][mu].at(0, 1)))-((imag(fundamentalLattice[site][mu].at(0, 1)))*(real(fundamentalLattice[site][mu].at(1, 0))))-((imag(fundamentalLattice[site][mu].at(0, 0)))*(real(fundamentalLattice[site][mu].at(1, 1))));
			adjointLattice[site][mu].at(3, 1) = (imag(fundamentalLattice[site][mu].at(1, 2)))*(real(fundamentalLattice[site][mu].at(0, 0)))+(imag(fundamentalLattice[site][mu].at(1, 0)))*(real(fundamentalLattice[site][mu].at(0, 2)))-((imag(fundamentalLattice[site][mu].at(0, 2)))*(real(fundamentalLattice[site][mu].at(1, 0))))-((imag(fundamentalLattice[site][mu].at(0, 0)))*(real(fundamentalLattice[site][mu].at(1, 2))));
			adjointLattice[site][mu].at(3, 2) = (imag(fundamentalLattice[site][mu].at(1, 2)))*(real(fundamentalLattice[site][mu].at(0, 1)))+(imag(fundamentalLattice[site][mu].at(1, 1)))*(real(fundamentalLattice[site][mu].at(0, 2)))-((imag(fundamentalLattice[site][mu].at(0, 2)))*(real(fundamentalLattice[site][mu].at(1, 1))))-((imag(fundamentalLattice[site][mu].at(0, 1)))*(real(fundamentalLattice[site][mu].at(1, 2))));
			adjointLattice[site][mu].at(3, 3) = -((imag(fundamentalLattice[site][mu].at(0, 1)))*(imag(fundamentalLattice[site][mu].at(1, 0))))+(imag(fundamentalLattice[site][mu].at(0, 0)))*(imag(fundamentalLattice[site][mu].at(1, 1)))-((real(fundamentalLattice[site][mu].at(0, 1)))*(real(fundamentalLattice[site][mu].at(1, 0))))+(real(fundamentalLattice[site][mu].at(0, 0)))*(real(fundamentalLattice[site][mu].at(1, 1)));
			adjointLattice[site][mu].at(3, 4) = -((imag(fundamentalLattice[site][mu].at(0, 2)))*(imag(fundamentalLattice[site][mu].at(1, 0))))+(imag(fundamentalLattice[site][mu].at(0, 0)))*(imag(fundamentalLattice[site][mu].at(1, 2)))-((real(fundamentalLattice[site][mu].at(0, 2)))*(real(fundamentalLattice[site][mu].at(1, 0))))+(real(fundamentalLattice[site][mu].at(0, 0)))*(real(fundamentalLattice[site][mu].at(1, 2)));
			adjointLattice[site][mu].at(3, 5) = -((imag(fundamentalLattice[site][mu].at(0, 2)))*(imag(fundamentalLattice[site][mu].at(1, 1))))+(imag(fundamentalLattice[site][mu].at(0, 1)))*(imag(fundamentalLattice[site][mu].at(1, 2)))-((real(fundamentalLattice[site][mu].at(0, 2)))*(real(fundamentalLattice[site][mu].at(1, 1))))+(real(fundamentalLattice[site][mu].at(0, 1)))*(real(fundamentalLattice[site][mu].at(1, 2)));
			adjointLattice[site][mu].at(3, 6) = (imag(fundamentalLattice[site][mu].at(1, 0)))*(real(fundamentalLattice[site][mu].at(0, 0)))-((imag(fundamentalLattice[site][mu].at(1, 1)))*(real(fundamentalLattice[site][mu].at(0, 1))))-((imag(fundamentalLattice[site][mu].at(0, 0)))*(real(fundamentalLattice[site][mu].at(1, 0))))+(imag(fundamentalLattice[site][mu].at(0, 1)))*(real(fundamentalLattice[site][mu].at(1, 1)));
			adjointLattice[site][mu].at(3, 7) = (imag(fundamentalLattice[site][mu].at(1, 0)))*(real(fundamentalLattice[site][mu].at(0, 0)))/sqrt(3)+(imag(fundamentalLattice[site][mu].at(1, 1)))*(real(fundamentalLattice[site][mu].at(0, 1)))/sqrt(3)+(-2)*((imag(fundamentalLattice[site][mu].at(1, 2)))*(real(fundamentalLattice[site][mu].at(0, 2))))/sqrt(3)-((imag(fundamentalLattice[site][mu].at(0, 0)))*(real(fundamentalLattice[site][mu].at(1, 0)))/sqrt(3))-((imag(fundamentalLattice[site][mu].at(0, 1)))*(real(fundamentalLattice[site][mu].at(1, 1)))/sqrt(3))+(2)*((imag(fundamentalLattice[site][mu].at(0, 2)))*(real(fundamentalLattice[site][mu].at(1, 2))))/sqrt(3);
			adjointLattice[site][mu].at(4, 0) = (imag(fundamentalLattice[site][mu].at(2, 1)))*(real(fundamentalLattice[site][mu].at(0, 0)))+(imag(fundamentalLattice[site][mu].at(2, 0)))*(real(fundamentalLattice[site][mu].at(0, 1)))-((imag(fundamentalLattice[site][mu].at(0, 1)))*(real(fundamentalLattice[site][mu].at(2, 0))))-((imag(fundamentalLattice[site][mu].at(0, 0)))*(real(fundamentalLattice[site][mu].at(2, 1))));
			adjointLattice[site][mu].at(4, 1) = (imag(fundamentalLattice[site][mu].at(2, 2)))*(real(fundamentalLattice[site][mu].at(0, 0)))+(imag(fundamentalLattice[site][mu].at(2, 0)))*(real(fundamentalLattice[site][mu].at(0, 2)))-((imag(fundamentalLattice[site][mu].at(0, 2)))*(real(fundamentalLattice[site][mu].at(2, 0))))-((imag(fundamentalLattice[site][mu].at(0, 0)))*(real(fundamentalLattice[site][mu].at(2, 2))));
			adjointLattice[site][mu].at(4, 2) = (imag(fundamentalLattice[site][mu].at(2, 2)))*(real(fundamentalLattice[site][mu].at(0, 1)))+(imag(fundamentalLattice[site][mu].at(2, 1)))*(real(fundamentalLattice[site][mu].at(0, 2)))-((imag(fundamentalLattice[site][mu].at(0, 2)))*(real(fundamentalLattice[site][mu].at(2, 1))))-((imag(fundamentalLattice[site][mu].at(0, 1)))*(real(fundamentalLattice[site][mu].at(2, 2))));
			adjointLattice[site][mu].at(4, 3) = -((imag(fundamentalLattice[site][mu].at(0, 1)))*(imag(fundamentalLattice[site][mu].at(2, 0))))+(imag(fundamentalLattice[site][mu].at(0, 0)))*(imag(fundamentalLattice[site][mu].at(2, 1)))-((real(fundamentalLattice[site][mu].at(0, 1)))*(real(fundamentalLattice[site][mu].at(2, 0))))+(real(fundamentalLattice[site][mu].at(0, 0)))*(real(fundamentalLattice[site][mu].at(2, 1)));
			adjointLattice[site][mu].at(4, 4) = -((imag(fundamentalLattice[site][mu].at(0, 2)))*(imag(fundamentalLattice[site][mu].at(2, 0))))+(imag(fundamentalLattice[site][mu].at(0, 0)))*(imag(fundamentalLattice[site][mu].at(2, 2)))-((real(fundamentalLattice[site][mu].at(0, 2)))*(real(fundamentalLattice[site][mu].at(2, 0))))+(real(fundamentalLattice[site][mu].at(0, 0)))*(real(fundamentalLattice[site][mu].at(2, 2)));
			adjointLattice[site][mu].at(4, 5) = -((imag(fundamentalLattice[site][mu].at(0, 2)))*(imag(fundamentalLattice[site][mu].at(2, 1))))+(imag(fundamentalLattice[site][mu].at(0, 1)))*(imag(fundamentalLattice[site][mu].at(2, 2)))-((real(fundamentalLattice[site][mu].at(0, 2)))*(real(fundamentalLattice[site][mu].at(2, 1))))+(real(fundamentalLattice[site][mu].at(0, 1)))*(real(fundamentalLattice[site][mu].at(2, 2)));
			adjointLattice[site][mu].at(4, 6) = (imag(fundamentalLattice[site][mu].at(2, 0)))*(real(fundamentalLattice[site][mu].at(0, 0)))-((imag(fundamentalLattice[site][mu].at(2, 1)))*(real(fundamentalLattice[site][mu].at(0, 1))))-((imag(fundamentalLattice[site][mu].at(0, 0)))*(real(fundamentalLattice[site][mu].at(2, 0))))+(imag(fundamentalLattice[site][mu].at(0, 1)))*(real(fundamentalLattice[site][mu].at(2, 1)));
			adjointLattice[site][mu].at(4, 7) = (imag(fundamentalLattice[site][mu].at(2, 0)))*(real(fundamentalLattice[site][mu].at(0, 0)))/sqrt(3)+(imag(fundamentalLattice[site][mu].at(2, 1)))*(real(fundamentalLattice[site][mu].at(0, 1)))/sqrt(3)+(-2)*((imag(fundamentalLattice[site][mu].at(2, 2)))*(real(fundamentalLattice[site][mu].at(0, 2))))/sqrt(3)-((imag(fundamentalLattice[site][mu].at(0, 0)))*(real(fundamentalLattice[site][mu].at(2, 0)))/sqrt(3))-((imag(fundamentalLattice[site][mu].at(0, 1)))*(real(fundamentalLattice[site][mu].at(2, 1)))/sqrt(3))+(2)*((imag(fundamentalLattice[site][mu].at(0, 2)))*(real(fundamentalLattice[site][mu].at(2, 2))))/sqrt(3);
			adjointLattice[site][mu].at(5, 0) = (imag(fundamentalLattice[site][mu].at(2, 1)))*(real(fundamentalLattice[site][mu].at(1, 0)))+(imag(fundamentalLattice[site][mu].at(2, 0)))*(real(fundamentalLattice[site][mu].at(1, 1)))-((imag(fundamentalLattice[site][mu].at(1, 1)))*(real(fundamentalLattice[site][mu].at(2, 0))))-((imag(fundamentalLattice[site][mu].at(1, 0)))*(real(fundamentalLattice[site][mu].at(2, 1))));
			adjointLattice[site][mu].at(5, 1) = (imag(fundamentalLattice[site][mu].at(2, 2)))*(real(fundamentalLattice[site][mu].at(1, 0)))+(imag(fundamentalLattice[site][mu].at(2, 0)))*(real(fundamentalLattice[site][mu].at(1, 2)))-((imag(fundamentalLattice[site][mu].at(1, 2)))*(real(fundamentalLattice[site][mu].at(2, 0))))-((imag(fundamentalLattice[site][mu].at(1, 0)))*(real(fundamentalLattice[site][mu].at(2, 2))));
			adjointLattice[site][mu].at(5, 2) = (imag(fundamentalLattice[site][mu].at(2, 2)))*(real(fundamentalLattice[site][mu].at(1, 1)))+(imag(fundamentalLattice[site][mu].at(2, 1)))*(real(fundamentalLattice[site][mu].at(1, 2)))-((imag(fundamentalLattice[site][mu].at(1, 2)))*(real(fundamentalLattice[site][mu].at(2, 1))))-((imag(fundamentalLattice[site][mu].at(1, 1)))*(real(fundamentalLattice[site][mu].at(2, 2))));
			adjointLattice[site][mu].at(5, 3) = -((imag(fundamentalLattice[site][mu].at(1, 1)))*(imag(fundamentalLattice[site][mu].at(2, 0))))+(imag(fundamentalLattice[site][mu].at(1, 0)))*(imag(fundamentalLattice[site][mu].at(2, 1)))-((real(fundamentalLattice[site][mu].at(1, 1)))*(real(fundamentalLattice[site][mu].at(2, 0))))+(real(fundamentalLattice[site][mu].at(1, 0)))*(real(fundamentalLattice[site][mu].at(2, 1)));
			adjointLattice[site][mu].at(5, 4) = -((imag(fundamentalLattice[site][mu].at(1, 2)))*(imag(fundamentalLattice[site][mu].at(2, 0))))+(imag(fundamentalLattice[site][mu].at(1, 0)))*(imag(fundamentalLattice[site][mu].at(2, 2)))-((real(fundamentalLattice[site][mu].at(1, 2)))*(real(fundamentalLattice[site][mu].at(2, 0))))+(real(fundamentalLattice[site][mu].at(1, 0)))*(real(fundamentalLattice[site][mu].at(2, 2)));
			adjointLattice[site][mu].at(5, 5) = -((imag(fundamentalLattice[site][mu].at(1, 2)))*(imag(fundamentalLattice[site][mu].at(2, 1))))+(imag(fundamentalLattice[site][mu].at(1, 1)))*(imag(fundamentalLattice[site][mu].at(2, 2)))-((real(fundamentalLattice[site][mu].at(1, 2)))*(real(fundamentalLattice[site][mu].at(2, 1))))+(real(fundamentalLattice[site][mu].at(1, 1)))*(real(fundamentalLattice[site][mu].at(2, 2)));
			adjointLattice[site][mu].at(5, 6) = (imag(fundamentalLattice[site][mu].at(2, 0)))*(real(fundamentalLattice[site][mu].at(1, 0)))-((imag(fundamentalLattice[site][mu].at(2, 1)))*(real(fundamentalLattice[site][mu].at(1, 1))))-((imag(fundamentalLattice[site][mu].at(1, 0)))*(real(fundamentalLattice[site][mu].at(2, 0))))+(imag(fundamentalLattice[site][mu].at(1, 1)))*(real(fundamentalLattice[site][mu].at(2, 1)));
			adjointLattice[site][mu].at(5, 7) = (imag(fundamentalLattice[site][mu].at(2, 0)))*(real(fundamentalLattice[site][mu].at(1, 0)))/sqrt(3)+(imag(fundamentalLattice[site][mu].at(2, 1)))*(real(fundamentalLattice[site][mu].at(1, 1)))/sqrt(3)+(-2)*((imag(fundamentalLattice[site][mu].at(2, 2)))*(real(fundamentalLattice[site][mu].at(1, 2))))/sqrt(3)-((imag(fundamentalLattice[site][mu].at(1, 0)))*(real(fundamentalLattice[site][mu].at(2, 0)))/sqrt(3))-((imag(fundamentalLattice[site][mu].at(1, 1)))*(real(fundamentalLattice[site][mu].at(2, 1)))/sqrt(3))+(2)*((imag(fundamentalLattice[site][mu].at(1, 2)))*(real(fundamentalLattice[site][mu].at(2, 2))))/sqrt(3);
			adjointLattice[site][mu].at(6, 0) = (imag(fundamentalLattice[site][mu].at(0, 0)))*(imag(fundamentalLattice[site][mu].at(0, 1)))-((imag(fundamentalLattice[site][mu].at(1, 0)))*(imag(fundamentalLattice[site][mu].at(1, 1))))+(real(fundamentalLattice[site][mu].at(0, 0)))*(real(fundamentalLattice[site][mu].at(0, 1)))-((real(fundamentalLattice[site][mu].at(1, 0)))*(real(fundamentalLattice[site][mu].at(1, 1))));
			adjointLattice[site][mu].at(6, 1) = (imag(fundamentalLattice[site][mu].at(0, 0)))*(imag(fundamentalLattice[site][mu].at(0, 2)))-((imag(fundamentalLattice[site][mu].at(1, 0)))*(imag(fundamentalLattice[site][mu].at(1, 2))))+(real(fundamentalLattice[site][mu].at(0, 0)))*(real(fundamentalLattice[site][mu].at(0, 2)))-((real(fundamentalLattice[site][mu].at(1, 0)))*(real(fundamentalLattice[site][mu].at(1, 2))));
			adjointLattice[site][mu].at(6, 2) = (imag(fundamentalLattice[site][mu].at(0, 1)))*(imag(fundamentalLattice[site][mu].at(0, 2)))-((imag(fundamentalLattice[site][mu].at(1, 1)))*(imag(fundamentalLattice[site][mu].at(1, 2))))+(real(fundamentalLattice[site][mu].at(0, 1)))*(real(fundamentalLattice[site][mu].at(0, 2)))-((real(fundamentalLattice[site][mu].at(1, 1)))*(real(fundamentalLattice[site][mu].at(1, 2))));
			adjointLattice[site][mu].at(6, 3) = -((imag(fundamentalLattice[site][mu].at(0, 1)))*(real(fundamentalLattice[site][mu].at(0, 0))))+(imag(fundamentalLattice[site][mu].at(0, 0)))*(real(fundamentalLattice[site][mu].at(0, 1)))+(imag(fundamentalLattice[site][mu].at(1, 1)))*(real(fundamentalLattice[site][mu].at(1, 0)))-((imag(fundamentalLattice[site][mu].at(1, 0)))*(real(fundamentalLattice[site][mu].at(1, 1))));
			adjointLattice[site][mu].at(6, 4) = -((imag(fundamentalLattice[site][mu].at(0, 2)))*(real(fundamentalLattice[site][mu].at(0, 0))))+(imag(fundamentalLattice[site][mu].at(0, 0)))*(real(fundamentalLattice[site][mu].at(0, 2)))+(imag(fundamentalLattice[site][mu].at(1, 2)))*(real(fundamentalLattice[site][mu].at(1, 0)))-((imag(fundamentalLattice[site][mu].at(1, 0)))*(real(fundamentalLattice[site][mu].at(1, 2))));
			adjointLattice[site][mu].at(6, 5) = -((imag(fundamentalLattice[site][mu].at(0, 2)))*(real(fundamentalLattice[site][mu].at(0, 1))))+(imag(fundamentalLattice[site][mu].at(0, 1)))*(real(fundamentalLattice[site][mu].at(0, 2)))+(imag(fundamentalLattice[site][mu].at(1, 2)))*(real(fundamentalLattice[site][mu].at(1, 1)))-((imag(fundamentalLattice[site][mu].at(1, 1)))*(real(fundamentalLattice[site][mu].at(1, 2))));
			adjointLattice[site][mu].at(6, 6) = 0.5*((imag(fundamentalLattice[site][mu].at(0, 0)))*(imag(fundamentalLattice[site][mu].at(0, 0))))+(((-1.)/(2.)))*((imag(fundamentalLattice[site][mu].at(0, 1)))*(imag(fundamentalLattice[site][mu].at(0, 1))))+(((-1.)/(2.)))*((imag(fundamentalLattice[site][mu].at(1, 0)))*(imag(fundamentalLattice[site][mu].at(1, 0))))+0.5*((imag(fundamentalLattice[site][mu].at(1, 1)))*(imag(fundamentalLattice[site][mu].at(1, 1))))+0.5*((real(fundamentalLattice[site][mu].at(0, 0)))*(real(fundamentalLattice[site][mu].at(0, 0))))+(((-1.)/(2.)))*((real(fundamentalLattice[site][mu].at(0, 1)))*(real(fundamentalLattice[site][mu].at(0, 1))))+(((-1.)/(2.)))*((real(fundamentalLattice[site][mu].at(1, 0)))*(real(fundamentalLattice[site][mu].at(1, 0))))+0.5*((real(fundamentalLattice[site][mu].at(1, 1)))*(real(fundamentalLattice[site][mu].at(1, 1))));
			adjointLattice[site][mu].at(6, 7) = 0.5*((imag(fundamentalLattice[site][mu].at(0, 0)))*(imag(fundamentalLattice[site][mu].at(0, 0)))/sqrt(3))+0.5*((imag(fundamentalLattice[site][mu].at(0, 1)))*(imag(fundamentalLattice[site][mu].at(0, 1)))/sqrt(3))-((imag(fundamentalLattice[site][mu].at(0, 2)))*(imag(fundamentalLattice[site][mu].at(0, 2)))/sqrt(3))+(((-1.)/(2.)))*((imag(fundamentalLattice[site][mu].at(1, 0)))*(imag(fundamentalLattice[site][mu].at(1, 0))))/sqrt(3)+(((-1.)/(2.)))*((imag(fundamentalLattice[site][mu].at(1, 1)))*(imag(fundamentalLattice[site][mu].at(1, 1))))/sqrt(3)+(imag(fundamentalLattice[site][mu].at(1, 2)))*(imag(fundamentalLattice[site][mu].at(1, 2)))/sqrt(3)+0.5*((real(fundamentalLattice[site][mu].at(0, 0)))*(real(fundamentalLattice[site][mu].at(0, 0)))/sqrt(3))+0.5*((real(fundamentalLattice[site][mu].at(0, 1)))*(real(fundamentalLattice[site][mu].at(0, 1)))/sqrt(3))-((real(fundamentalLattice[site][mu].at(0, 2)))*(real(fundamentalLattice[site][mu].at(0, 2)))/sqrt(3))+(((-1.)/(2.)))*((real(fundamentalLattice[site][mu].at(1, 0)))*(real(fundamentalLattice[site][mu].at(1, 0))))/sqrt(3)+(((-1.)/(2.)))*((real(fundamentalLattice[site][mu].at(1, 1)))*(real(fundamentalLattice[site][mu].at(1, 1))))/sqrt(3)+(real(fundamentalLattice[site][mu].at(1, 2)))*(real(fundamentalLattice[site][mu].at(1, 2)))/sqrt(3);
			adjointLattice[site][mu].at(7, 0) = (imag(fundamentalLattice[site][mu].at(0, 0)))*(imag(fundamentalLattice[site][mu].at(0, 1)))/sqrt(3)+(imag(fundamentalLattice[site][mu].at(1, 0)))*(imag(fundamentalLattice[site][mu].at(1, 1)))/sqrt(3)+(-2)*((imag(fundamentalLattice[site][mu].at(2, 0)))*(imag(fundamentalLattice[site][mu].at(2, 1))))/sqrt(3)+(real(fundamentalLattice[site][mu].at(0, 0)))*(real(fundamentalLattice[site][mu].at(0, 1)))/sqrt(3)+(real(fundamentalLattice[site][mu].at(1, 0)))*(real(fundamentalLattice[site][mu].at(1, 1)))/sqrt(3)+(-2)*((real(fundamentalLattice[site][mu].at(2, 0)))*(real(fundamentalLattice[site][mu].at(2, 1))))/sqrt(3);
			adjointLattice[site][mu].at(7, 1) = (imag(fundamentalLattice[site][mu].at(0, 0)))*(imag(fundamentalLattice[site][mu].at(0, 2)))/sqrt(3)+(imag(fundamentalLattice[site][mu].at(1, 0)))*(imag(fundamentalLattice[site][mu].at(1, 2)))/sqrt(3)+(-2)*((imag(fundamentalLattice[site][mu].at(2, 0)))*(imag(fundamentalLattice[site][mu].at(2, 2))))/sqrt(3)+(real(fundamentalLattice[site][mu].at(0, 0)))*(real(fundamentalLattice[site][mu].at(0, 2)))/sqrt(3)+(real(fundamentalLattice[site][mu].at(1, 0)))*(real(fundamentalLattice[site][mu].at(1, 2)))/sqrt(3)+(-2)*((real(fundamentalLattice[site][mu].at(2, 0)))*(real(fundamentalLattice[site][mu].at(2, 2))))/sqrt(3);
			adjointLattice[site][mu].at(7, 2) = (imag(fundamentalLattice[site][mu].at(0, 1)))*(imag(fundamentalLattice[site][mu].at(0, 2)))/sqrt(3)+(imag(fundamentalLattice[site][mu].at(1, 1)))*(imag(fundamentalLattice[site][mu].at(1, 2)))/sqrt(3)+(-2)*((imag(fundamentalLattice[site][mu].at(2, 1)))*(imag(fundamentalLattice[site][mu].at(2, 2))))/sqrt(3)+(real(fundamentalLattice[site][mu].at(0, 1)))*(real(fundamentalLattice[site][mu].at(0, 2)))/sqrt(3)+(real(fundamentalLattice[site][mu].at(1, 1)))*(real(fundamentalLattice[site][mu].at(1, 2)))/sqrt(3)+(-2)*((real(fundamentalLattice[site][mu].at(2, 1)))*(real(fundamentalLattice[site][mu].at(2, 2))))/sqrt(3);
			adjointLattice[site][mu].at(7, 3) = -((imag(fundamentalLattice[site][mu].at(0, 1)))*(real(fundamentalLattice[site][mu].at(0, 0)))/sqrt(3))+(imag(fundamentalLattice[site][mu].at(0, 0)))*(real(fundamentalLattice[site][mu].at(0, 1)))/sqrt(3)-((imag(fundamentalLattice[site][mu].at(1, 1)))*(real(fundamentalLattice[site][mu].at(1, 0)))/sqrt(3))+(imag(fundamentalLattice[site][mu].at(1, 0)))*(real(fundamentalLattice[site][mu].at(1, 1)))/sqrt(3)+(2)*((imag(fundamentalLattice[site][mu].at(2, 1)))*(real(fundamentalLattice[site][mu].at(2, 0))))/sqrt(3)+(-2)*((imag(fundamentalLattice[site][mu].at(2, 0)))*(real(fundamentalLattice[site][mu].at(2, 1))))/sqrt(3);
			adjointLattice[site][mu].at(7, 4) = -((imag(fundamentalLattice[site][mu].at(0, 2)))*(real(fundamentalLattice[site][mu].at(0, 0)))/sqrt(3))+(imag(fundamentalLattice[site][mu].at(0, 0)))*(real(fundamentalLattice[site][mu].at(0, 2)))/sqrt(3)-((imag(fundamentalLattice[site][mu].at(1, 2)))*(real(fundamentalLattice[site][mu].at(1, 0)))/sqrt(3))+(imag(fundamentalLattice[site][mu].at(1, 0)))*(real(fundamentalLattice[site][mu].at(1, 2)))/sqrt(3)+(2)*((imag(fundamentalLattice[site][mu].at(2, 2)))*(real(fundamentalLattice[site][mu].at(2, 0))))/sqrt(3)+(-2)*((imag(fundamentalLattice[site][mu].at(2, 0)))*(real(fundamentalLattice[site][mu].at(2, 2))))/sqrt(3);
			adjointLattice[site][mu].at(7, 5) = -((imag(fundamentalLattice[site][mu].at(0, 2)))*(real(fundamentalLattice[site][mu].at(0, 1)))/sqrt(3))+(imag(fundamentalLattice[site][mu].at(0, 1)))*(real(fundamentalLattice[site][mu].at(0, 2)))/sqrt(3)-((imag(fundamentalLattice[site][mu].at(1, 2)))*(real(fundamentalLattice[site][mu].at(1, 1)))/sqrt(3))+(imag(fundamentalLattice[site][mu].at(1, 1)))*(real(fundamentalLattice[site][mu].at(1, 2)))/sqrt(3)+(2)*((imag(fundamentalLattice[site][mu].at(2, 2)))*(real(fundamentalLattice[site][mu].at(2, 1))))/sqrt(3)+(-2)*((imag(fundamentalLattice[site][mu].at(2, 1)))*(real(fundamentalLattice[site][mu].at(2, 2))))/sqrt(3);
			adjointLattice[site][mu].at(7, 6) = 0.5*((imag(fundamentalLattice[site][mu].at(0, 0)))*(imag(fundamentalLattice[site][mu].at(0, 0)))/sqrt(3))+(((-1.)/(2.)))*((imag(fundamentalLattice[site][mu].at(0, 1)))*(imag(fundamentalLattice[site][mu].at(0, 1))))/sqrt(3)+0.5*((imag(fundamentalLattice[site][mu].at(1, 0)))*(imag(fundamentalLattice[site][mu].at(1, 0)))/sqrt(3))+(((-1.)/(2.)))*((imag(fundamentalLattice[site][mu].at(1, 1)))*(imag(fundamentalLattice[site][mu].at(1, 1))))/sqrt(3)-((imag(fundamentalLattice[site][mu].at(2, 0)))*(imag(fundamentalLattice[site][mu].at(2, 0)))/sqrt(3))+(imag(fundamentalLattice[site][mu].at(2, 1)))*(imag(fundamentalLattice[site][mu].at(2, 1)))/sqrt(3)+0.5*((real(fundamentalLattice[site][mu].at(0, 0)))*(real(fundamentalLattice[site][mu].at(0, 0)))/sqrt(3))+(((-1.)/(2.)))*((real(fundamentalLattice[site][mu].at(0, 1)))*(real(fundamentalLattice[site][mu].at(0, 1))))/sqrt(3)+0.5*((real(fundamentalLattice[site][mu].at(1, 0)))*(real(fundamentalLattice[site][mu].at(1, 0)))/sqrt(3))+(((-1.)/(2.)))*((real(fundamentalLattice[site][mu].at(1, 1)))*(real(fundamentalLattice[site][mu].at(1, 1))))/sqrt(3)-((real(fundamentalLattice[site][mu].at(2, 0)))*(real(fundamentalLattice[site][mu].at(2, 0)))/sqrt(3))+(real(fundamentalLattice[site][mu].at(2, 1)))*(real(fundamentalLattice[site][mu].at(2, 1)))/sqrt(3);
			adjointLattice[site][mu].at(7, 7) = (((1.)/(6.)))*((imag(fundamentalLattice[site][mu].at(0, 0)))*(imag(fundamentalLattice[site][mu].at(0, 0))))+(((1.)/(6.)))*((imag(fundamentalLattice[site][mu].at(0, 1)))*(imag(fundamentalLattice[site][mu].at(0, 1))))+(((-1.)/(3.)))*((imag(fundamentalLattice[site][mu].at(0, 2)))*(imag(fundamentalLattice[site][mu].at(0, 2))))+(((1.)/(6.)))*((imag(fundamentalLattice[site][mu].at(1, 0)))*(imag(fundamentalLattice[site][mu].at(1, 0))))+(((1.)/(6.)))*((imag(fundamentalLattice[site][mu].at(1, 1)))*(imag(fundamentalLattice[site][mu].at(1, 1))))+(((-1.)/(3.)))*((imag(fundamentalLattice[site][mu].at(1, 2)))*(imag(fundamentalLattice[site][mu].at(1, 2))))+(((-1.)/(3.)))*((imag(fundamentalLattice[site][mu].at(2, 0)))*(imag(fundamentalLattice[site][mu].at(2, 0))))+(((-1.)/(3.)))*((imag(fundamentalLattice[site][mu].at(2, 1)))*(imag(fundamentalLattice[site][mu].at(2, 1))))+(((2.)/(3.)))*((imag(fundamentalLattice[site][mu].at(2, 2)))*(imag(fundamentalLattice[site][mu].at(2, 2))))+(((1.)/(6.)))*((real(fundamentalLattice[site][mu].at(0, 0)))*(real(fundamentalLattice[site][mu].at(0, 0))))+(((1.)/(6.)))*((real(fundamentalLattice[site][mu].at(0, 1)))*(real(fundamentalLattice[site][mu].at(0, 1))))+(((-1.)/(3.)))*((real(fundamentalLattice[site][mu].at(0, 2)))*(real(fundamentalLattice[site][mu].at(0, 2))))+(((1.)/(6.)))*((real(fundamentalLattice[site][mu].at(1, 0)))*(real(fundamentalLattice[site][mu].at(1, 0))))+(((1.)/(6.)))*((real(fundamentalLattice[site][mu].at(1, 1)))*(real(fundamentalLattice[site][mu].at(1, 1))))+(((-1.)/(3.)))*((real(fundamentalLattice[site][mu].at(1, 2)))*(real(fundamentalLattice[site][mu].at(1, 2))))+(((-1.)/(3.)))*((real(fundamentalLattice[site][mu].at(2, 0)))*(real(fundamentalLattice[site][mu].at(2, 0))))+(((-1.)/(3.)))*((real(fundamentalLattice[site][mu].at(2, 1)))*(real(fundamentalLattice[site][mu].at(2, 1))))+(((2.)/(3.)))*((real(fundamentalLattice[site][mu].at(2, 2)))*(real(fundamentalLattice[site][mu].at(2, 2))));
#endif
#if NUMCOLORS > 3
			std::cout << "Number of colors " << NUMCOLORS << "not supported in adjoint mode" << std::endl;
			exit(1);
#endif
		}
	}
	adjointLattice.updateHalo();//TODO is needed?
}

template<> void ConvertLattice::convert<extended_fermion_lattice_t,extended_gauge_lattice_t>(extended_fermion_lattice_t&, const extended_gauge_lattice_t&);

} /* namespace Update */
